# Generated by Django 5.0.4 on 2024-05-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('display_text', models.CharField(max_length=30)),
                ('icon_url', models.CharField(max_length=100)),
            ],
        ),
    ]
