# Generated by Django 5.0.4 on 2024-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesection',
            name='navigation_url',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
