# Generated by Django 5.0.4 on 2024-05-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesection_navigation_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesection',
            old_name='navigation_url',
            new_name='navigation_path_name',
        ),
    ]
