# Generated by Django 5.0.4 on 2024-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_navigation_url_sitesection_navigation_path_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='display_text',
            field=models.CharField(max_length=30, verbose_name='Display Text'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='icon_url',
            field=models.CharField(max_length=100, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='navigation_path_name',
            field=models.CharField(default='#', max_length=100, verbose_name='Path Name'),
        ),
    ]
