# Generated by Django 5.0.4 on 2024-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sitesection_display_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(default='', max_length=30, verbose_name='Display Text')),
                ('icon_url', models.CharField(default='', max_length=100, verbose_name='Icon URL')),
                ('navigation_path_name', models.CharField(default='#', max_length=100, verbose_name='Path Name')),
                ('parent_id', models.IntegerField(verbose_name='Parent ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='display_text',
            field=models.CharField(default='', max_length=30, verbose_name='Display Text'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='icon_url',
            field=models.CharField(default='', max_length=100, verbose_name='Icon URL'),
        ),
    ]
