# Generated by Django 5.0.4 on 2024-05-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sidebarsection_alter_sitesection_display_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarsection',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='sidebarsection',
            name='parent',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.sidebarsection', verbose_name='Parent'),
        ),
    ]
