# Generated by Django 5.0.4 on 2024-05-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_sidebarsection_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarsection',
            name='display_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Display Text'),
        ),
        migrations.AlterField(
            model_name='sidebarsection',
            name='icon_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='sidebarsection',
            name='navigation_path_name',
            field=models.CharField(blank=True, default='#', max_length=100, verbose_name='Path Name'),
        ),
        migrations.AlterField(
            model_name='sidebarsection',
            name='parent',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.sidebarsection', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='display_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='Display Text'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='icon_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='navigation_path_name',
            field=models.CharField(blank=True, default='#', max_length=100, verbose_name='Path Name'),
        ),
    ]
