# Generated by Django 5.0.4 on 2024-05-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sidebarsection_display_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarsection',
            name='parent',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.sidebarsection', verbose_name='Parent'),
        ),
    ]
