# Generated by Django 5.0.4 on 2024-05-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_sidebarsection_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Build ID')),
                ('display_text', models.CharField(max_length=10, verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='IDE',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=100, verbose_name='IDE Name')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalSystem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=100, verbose_name='OS Name')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Platform ID')),
                ('display_text', models.CharField(max_length=500, verbose_name='Platform Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('display_text', models.CharField(max_length=500, verbose_name='Product Name')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Ticket Number')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('creation_date', models.DateField(verbose_name='Date of Creation')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.build', verbose_name='Build Version')),
                ('ide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ide', verbose_name='IDE')),
                ('operational_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.operationalsystem', verbose_name='OS')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.platform', verbose_name='Platform')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Product')),
            ],
        ),
    ]
